services:
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports:
            - '5672:5672' # AMQP port
            - '15672:15672' # Management UI port
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        networks:
            - rabbitmq-network
    postgres:
        image: postgres:15
        container_name: postgres
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - rabbitmq-network

volumes:
    rabbitmq-data:
    postgres-data:

networks:
    rabbitmq-network:
        driver: bridge
