services:
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports:
            - '5672:5672' # AMQP port
            - '15672:15672' # Management UI port
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        networks:
            - rabbitmq-network
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - '27017:27017'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
            - MONGO_INITDB_DATABASE=admin
        volumes:
            - mongodb-data:/var/lib/mongodb/data
        networks:
            - rabbitmq-network

volumes:
    rabbitmq-data:
    mongodb-data:

networks:
    rabbitmq-network:
        driver: bridge
