@baseUrl = http://localhost:3000

### Sign up
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
    "email": "khang.nt@gmail.com",
    "password": "123456",
    "firstName": "Khang",
    "lastName": "Nguyen Thuc",
    "role": "USER"
}